- CHANGELOG.md
- README.md
- config-handlers/ProxyConfig.groovy
- init-scripts/JenkinsConfigLoader.groovy
> Proxy config

- config-handlers/ProxyConfig.groovy
> Download all downloadables when proxy is set

- CHANGELOG.md
- README.md
- config-handlers/EnvironmentVarsConfig.groovy
- init-scripts/JenkinsConfigLoader.groovy
> Environment vars

- CHANGELOG.md
- jenkins.sh
> Docker socket group

- CHANGELOG.md
- Dockerfile
- README.md
- jenkins.sh
> Watch file

- CHANGELOG.md
- config-handlers/GeneralConfig.groovy
- config-handlers/ProxyConfig.groovy
- init-scripts/JenkinsConfigLoader.groovy
- plugins.txt
> Handle downloadable services on generalconfig

- CHANGELOG.md
- Dockerfile
- README.md
- examples/docker/config.yml
- examples/docker/docker-compose.yml
- init-scripts/JenkinsConfigLoader.groovy
- jenkins.sh
- tests/run-test.sh
- update-config.sh
moved the config file and token file to be ENV vars and store them by default within the /dev/shm directory
> Config file should be stored in tmpfs by default for security reasons

- CHANGELOG.md
- README.md
- jenkins.sh
> Install plugins on start

- CHANGELOG.md
- README.md
- config-handlers/CredsConfig.groovy
- tests/groovy/CredsConfigTest.groovy
> implementing dynamic creds

- CHANGELOG.md
- README.md
- config-handlers/CloudsConfig.groovy
- tests/groovy/CloudsConfigTest.groovy
FARGATE must have an iam role attached to task.
Relates to #96 
```
clouds:
ecs-cloud:
type: ecs
templates:
- name: ecsSlave
......
.......
launchType: FARGATE
securityGroups: sg-123,sg-456         # comma separated security groups
assignPublicIp: false                 # default fals
subnets: 192.10.0.0/21,192.12.0.0/21  # comma separated subnets
taskrole: <TASK_ROLE_ARN>
```
> added taskrole

- README.md
- config-handlers/ArtifactoryConfig.groovy
- init-scripts/JenkinsConfigLoader.groovy
- tests/config-handlers-tests.bats
- tests/groovy/config-handlers/ArtifactoryConfigTest.groovy
- tests/groovy/config-handlers/CheckmarxConfigTest.groovy
> Artifactory config

- README.md
- config-handlers/SeedJobsConfig.groovy
Supported since artifactory-jenkins-plugin 3.0.0
> Support trigger by polling Artifactory

- README.md
- config-handlers/ToolsConfig.groovy
- plugins.txt
[Branch] feature/add-golang-tool
I've built the image locally and test it OK locally.
I don't know the project test framework yet, so I didn't add a case for it in the test class.
> Add Golang tool

- README.md
- config-handlers/NotifiersConfig.groovy
- plugins.txt
- tests/groovy/config-handlers/NotifiersConfigTest.groovy
> Removed hipchat

- Dockerfile
- config-handlers/SonarQubeServersConfig.groovy
- tests/groovy/config-handlers/SonarQubeServersConfigTest.groovy
serverAuthenticationToken is deprecated
> hudson.plugins.sonar.SonarInstallation is using credentialsId

- README.md
Fixes https://github.com/odavid/jenkins-jnlp-slave/issues/13
> Adding example of resource limits in kubernetes cloud - [skip ci]

- README.md
- config-handlers/CloudsConfig.groovy
- tests/groovy/config-handlers/CloudsConfigTest.groovy
> Time in minutes to retain agent when idle for kubernetes

- README.md
- config-handlers/SecurityConfig.groovy
- plugins.txt
- tests/groovy/config-handlers/SecurityConfigTest.groovy
Following changes are:
- Adds support to use OpenID Connect to authenticate using self-hosted or public OpenID connect providers.
> Adds support to use OpenID Connect Auth

- config-handlers/SeedJobsConfig.groovy
- tests/groovy/config-handlers/SeedJobsConfigTest.groovy
Fixed issue with SeedJobs when jobs located in subfolders which nesting > 1
> Fixed issue with SeedJobs in subfolders which nesting > 1

- README.md
- config-handlers/SeedJobsConfig.groovy
- tests/groovy/config-handlers/SeedJobsConfigTest.groovy
Adds ability to set concurrentBuild=true per pipeline.
> Adds ability to set concurrentBuild=true

- README.md
- config-handlers/CloudsConfig.groovy
- tests/groovy/config-handlers/CloudsConfigTest.groovy
> Added runAsUser, runAsGroup and supplementalGroups for k8s plugin 

- README.md
updated readme to fix #210
for docker-cloud replaced volume syntax with mount syntax
> updated readme to fix #210
